

export const MESSAGE_TYPES = {
    SEND: "SEND_MESSAGE",
    CREATE_ROOM: "CREATE_ROOM",
    ROOM_CREATED: "ROOM_CREATED",
    ROOM_CREATED_FAILED: "ROOM_CREATION_FAILED",
    MESSAGE_RECEIVED: "NEW_MESSAGE_RECEIVED",
    SET_MESSAGE_DELIVERED: "SET_MESSAGE_DELIVERED",
    MESSAGE_DELIVERED: "MESSAGE_DELIVERED",
    GET_BACK_CREATED_MESSAGE: "OWN_MESSAGE_SAVED",
    SET_LIST_OF_MESSAGE_DELIVERED: "SET_LIST_OF_MESSAGES_DELIVERED",
    RECEIVE_LIST_OF_MESSAGE_DELIVERED: "LIST_OF_MESSAGES_DELIVERED",
    SET_SEEN_MESSAGE: "SET_MESSAGE_SEEN",
    RECEIVE_SEEN_MESSAGE: "MESSAGE_SEEN",
    FILE_MESSAGE_SEND_TO_OTHER_USER: "FILE_MESSAGE_SENT",
    FILE_MESSAGE_RECEIVE_TO_OTHER_USER: "FILE_MESSAGE_RECEIVED"
}

export const USER_HANDLES = {
    NEW_CONNECTION: "USER_CONNECTED",
    REMOVE_CONNECTION: "USER_DISCONNECTED",
    IS_FRIEND_IS_ONLINE: "CHECK_FRIEND_ONLINE",
    RECEIVE_FRIEND_IS_ONLINE: "FRIEND_ONLINE_STATUS",
    SHARE_MY_ONLINE_STATE: "SHARE_MY_ONLINE_STATUS"
}



export const CALL_TYPES = {
    CALL_OFFER_CREATED: "CALL_OFFER_CREATED",
    CALL_OFFER_RECEIVED: "CALL_OFFER_RECEIVED",
    CALL_ANSWER_CREATED: "CALL_ANSWER_CREATED",
    CALL_ANSWER_RECEIVED: "CALL_ANSWER_RECEIVED",
    CALL_ICE_NEW_CANDIDATE_CREATED: "CALL_ICE_CANDIDATE_CREATED",
    CALL_ICE_NEW_CANDIDATE_RECEIVED: "CALL_ICE_CANDIDATE_RECEIVED",
    CALL_WAS_DISCONNECTED_BY_USER: "CALL_DISCONNECTED",
    CALL_WAS_DISCONNECTED_BY_USER_RECEIVED: "CALL_DISCONNECTED_RECEIVED",

}

export const MAIN_HANDLERS = {
    USER_CONFIG: "USER_CONFIG",
    FILE_SHARE: "FILE_SHARE",
    MESSAGE: "MESSAGE",
    CALL: "CALL"
}

export const STORE_EVENTS = {
    MESSAGE_ADDED:"STORE_NEW_MESSAGE_ADDED",
    CALLING_CONTACT_SET:"CALLING_CONTACT_SET"
}

export const VISUAL_EVENTS = {
    MESSAGE_HAS_BEEN_READ_BY_USER:"VISUAL_MESSAGE_HAS_BEEN_READ_BY_USER",
    ADD_NEW_MESSAGE_BY_USER:"VISUAL_ADD_NEW_MESSAGE_BY_USER"
}

export const CLICK_EVENTS = {
    CALL_ACCEPT:"UI_CALL_ACCEPT_CLICKED"
}





// FILES

export const FILE_TYPES = {
    FILE_CREATE: "FILE_CREATE",
    FILE_CHUNK_TO_SERVER: "FILE_CHUNK_TO_SERVER",
    FILE_CHUNK_TO_CLIENT: "FILE_CHUNK_TO_CLIENT",
    FILE_CHUNK_FINISHED: "FILE_CHUNK_FINISHED",
    FILE_CREATED: "FILE_CREATED"
}

export const FILE_EVENTS = {
    FILES_ADDED:"file_add_files",
    FILE_UPLOAD_SHOW:"file_show_upload",
    FILE_UPLOAD_HIDE:"file_hide_upload",
    FILE_UPLOAD_PREVIEW:"file_upload_preview",
    FILE_PROGRESS_MADE:"file_upload_progress",
    FILE_UPLOAD_FINISHED:"file_upload_finished",
}

export const FILE_INTERACTIONS = {
    FILE_UPLOAD_DIALOG_OPEN:"file_open_upload_dialog",
    FILE_UPLOAD_DIALOG_CLOSE:"file_close_upload_dialog",
    FILE_SET_UPLOAD_PREVIEWS:"file_on_upload_previews",
    FILES_UPLOAD:"file_on_upload"
}